export const posts = [
  {
    id: 1,
    title: "Options Trading Basics For Beginners",
    author: "Samuel Choi",
    date: "March 14, 2024",
    thumbnail: "assets/options-image.avif",
    profile_pic: "assets/samuel-choi.png",
  },
  {
    id: 2,
    title: "Key Options Trading Terms and Concepts",
    author: "Samuel Choi",
    date: "March 14, 2024",
    thumbnail: "assets/key-options.avif",
    profile_pic: "assets/samuel-choi.png",
  },
  {
    id: 3,
    title: "Complementary Analysis Methods",
    author: "Michael Faletti",
    date: "March 14, 2024",
    thumbnail: "assets/complementary.avif",
    profile_pic: "assets/michael_faletti.png",
  },
  {
    id: 4,
    title: "Spotting Opportunities in Early Investment Trendsg",
    author: "Samuel Choi",
    date: "March 14, 2024",
    thumbnail: "assets/opportunities.avif",
    profile_pic: "assets/samuel-choi.png",
  },
  {
    id: 5,
    title: "Early Trend Analysis in Investing",
    author: "Michael Faletti",
    date: "March 14, 2024",
    thumbnail: "assets/options-image.avif",
    profile_pic: "assets/michael_faletti.png",
  },
  {
    id: 6,
    title: "The Evolution of Trend Analysis in the Investment Sphere",
    author: "Samuel Choi",
    date: "March 14, 2024",
    thumbnail: "assets/key-options.avif",
    profile_pic: "assets/samuel-choi.png",
  },
  {
    id: 7,
    title: "External Factors Influencing Trends",
    author: "Michael Faletti",
    date: "March 14, 2024",
    thumbnail: "assets/complementary.avif",
    profile_pic: "assets/michael_faletti.png",
  },
  {
    id: 8,
    title: "Education and Advisory in Investing",
    author: "Samuel Choi",
    date: "March 13, 2024",
    thumbnail: "assets/opportunities.avif",
    profile_pic: "assets/samuel-choi.png",
  },
];
